version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "vvti"
      POSTGRES_USER: "yutfut"
      POSTGRES_PASSWORD: "example"
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data/
      - ./init_db/:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    links:
        - "db:db"
    ports:
      - "8090:8080"

  memcached:
    image: 'memcached:latest'
    ports:
      - '11211:11211'

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus:/etc/prometheus"

  grafana:
    image: grafana/grafana-enterprise:8.2.0
    links:
      - "prometheus:prometheus"
    ports:
      - "3000:3000"
    user: '472'
