[server]
bindAddr = ":8081"

[authManager]
key="!@1eqQWERwer$%^YWFgsfghw$%%^E67ws"
method="HS256"
expiryTime="168h" #duration type

[notificator]
apiKey="PkzvymZDAVs0qasTSsdz1bxhhA"
email="nat-s.skv@yandex.ru"

[database]
user = "yutfut" # TODO установить норм имя
password = "example"
port = 5432
host = "127.0.0.1"
connectionMax = 500
dbname = "vvti"
# dbname = "test"

[cacher]
host = "127.0.0.1"
port = 11211