[server]
bindAddr = ":8081"

[authManager]
key="!@1eqQWERwer$%^YWFgsfghw$%%^E67ws"
method="HS256"
expiryTime="168h" #duration type

[notificator]
apiKey="PkzvymZDAVs0qasTSsdz1bxhhA"
email="nat-s.skv@yandex.ru"

[database]
user = "yutfut" # TODO установить норм имя
password = ${{ secrets.DB_PASSWORD }}
port = 5432
host = "db"
connectionMax = 500
dbname = "vvti"

[cacher]
host = "memcached"
port = 11211