[server]
bindAddr = ":8080"
readTimeout = 10
writeTimeout= 10
staticPath="static/"
staticUrl="http://tavide.xyz:8080/static/"

[cors]
allowOrigins=["", "http://95.163.180.8:3000", "http://localhost:3000", "http://tavide.xyz:3000"]
maxAge=86400

[csrf]
maxAge=604800 # 7 суток, как и токен авторизации


[logger]
level = "debug"
encoding = "json"
outputPaths = ["../access_log"]
errorOutputPaths = ["../error_log"]
messageKey = "msg"
timeKey = "finished"
levelKey = "lvl"
namekey  = "name" 
# functionKey = "funclion"
# stacktraceKey = "stack_trace"

[authManager]
key="!@1eqQWERwer$%^YWFgsfghw$%%^E67ws"
method="HS256"
expiryTime="168h" #duration type

[notificator]
apiKey="PkzvymZDAVs0qasTSsdz1bxhhA"
email="nat-s.skv@yandex.ru"

[database]
user = "yutfut" # TODO установить норм имя
password = "example"
port = 5432
host = "db"
connectionMax = 500
dbname = "vvti"

[cacher]
host = "memcached"
port = 11211