[server]
bindAddr = ":8080"
readTimeout = 10
writeTimeout= 10
allowOrigins=["", "http://localhost:3000", "http://tavide.xyz:3000"]

[logger]
level = "debug"
encoding = "json"
outputPaths = ["../access_log"]
errorOutputPaths = ["../error_log"]
messageKey = "msg"
timeKey = "finished"
levelKey = "lvl"
namekey  = "name" 
# functionKey = "funclion"
# stacktraceKey = "stack_trace"

[authManager]
key="!@1eqQWERwer$%^YWFgsfghw$%%^E67ws"
method="HS256"
expiryTime="168h" #duration type

[notificator]
apiKey="PkzvymZDAVs0qasTSsdz1bxhhA"
email="nat-s.skv@yandex.ru"

[database]
user = "postgres" # TODO установить норм имя
password = "1"
port = 5432
host = "127.0.0.1"
connectionMax = 500
dbname = "foobrinto"

[cacher]
host = "127.0.0.1"
port = 11211