authMicroserviceAddr = "auth:8081"
orderMicroserviceAddr = "order:8082"

[server]
bindAddr = ":8080"
readTimeout = 10
writeTimeout= 10
staticPath="static/"
staticUrl="https://tavide.xyz/static/"

[cors]
allowOrigins=["", "http://95.163.180.8:80", "http://localhost:3000", "http://tavide.xyz:3000"]
maxAge=86400

[csrf]
maxAge=604800 # 7 суток, как и токен авторизации


[logger]
level = "debug"
encoding = "json"
outputPaths = ["../access_log"]
errorOutputPaths = ["../error_log"]
messageKey = "msg"
timeKey = "finished"
levelKey = "lvl"
namekey  = "name"

[authManager]
key=${{ secrets.KEY }}
method="HS256"
expiryTime="168h" #duration type

[notificator]
apiKey=${{ secrets.APIKEY }}
email="nat-s.skv@yandex.ru"

[database]
user = "yutfut"
password = ${{ secrets.DB_PASSWORD }}
port = 5432
host = "db"
connectionMax = 500
dbname = "vvti"

[cacher]
host = "memcached"
port = 11211