basePath: /api/v1
definitions:
  models.CommentDataDelivery:
    properties:
      commentRating:
        type: integer
      commentText:
        type: string
      id:
        type: integer
      restaurants:
        type: integer
      userId:
        type: integer
    type: object
  models.CommentsDataDelivery:
    properties:
      comment:
        items:
          $ref: '#/definitions/models.CommentDataDelivery'
        type: array
    type: object
  models.DishJsonForKirill:
    properties:
      description:
        type: string
      id:
        type: integer
      imgPath:
        type: string
      info:
        type: integer
      price:
        type: integer
      productName:
        type: string
      restaurany:
        type: integer
      weight:
        type: integer
    type: object
  models.RestaurantJsonForKirill:
    properties:
      address:
        type: string
      city:
        type: string
      id:
        type: integer
      imgPath:
        type: string
      min_price:
        type: integer
      price:
        type: integer
      rating:
        type: number
      restName:
        type: string
      slug:
        type: string
      timeToDeliver:
        type: string
    type: object
  models.RestaurantsDishesJsonForKirill:
    properties:
      address:
        type: string
      avgPrice:
        type: integer
      city:
        type: string
      dishes:
        items:
          $ref: '#/definitions/models.DishJsonForKirill'
        type: array
      id:
        type: integer
      imgPath:
        type: string
      minPrice:
        type: integer
      rating:
        type: number
      restName:
        type: string
      slug:
        type: string
      timeToDeliver:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /comment:
    post:
      consumes:
      - application/json
      description: Add comments by restaurant
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CommentDataDelivery'
      summary: Add comments by restaurant
      tags:
      - Comments
  /comments/:id:
    get:
      consumes:
      - application/json
      description: get comments by restaurant
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CommentsDataDelivery'
      summary: List comments by restaurant
      tags:
      - Comments
  /restaurant/:slug:
    get:
      consumes:
      - application/json
      description: get dishes by restaurant
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.RestaurantsDishesJsonForKirill'
      summary: List dishes by restaurant
      tags:
      - Restaurants
  /restaurants:
    get:
      consumes:
      - application/json
      description: Get restaurants
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.RestaurantJsonForKirill'
            type: array
      summary: List restaurants
      tags:
      - Restaurants
swagger: "2.0"
