name: Docker Build

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build Docker image back
        run: docker build -f=Dockerfile -t yutfut/vvti_back:${GITHUB_SHA::8} .
      - name: Push the image bcak
        run: docker push yutfut/vvti_back:${GITHUB_SHA::8}
      - name: Build Docker image auth
        run: docker build -f=auth.Dockerfile -t yutfut/vvti_auth:${GITHUB_SHA::8} .
      - name: Push the image auth
        run: docker push yutfut/vvti_auth:${GITHUB_SHA::8}
      - name: Build Docker image order
        run: docker build -f=order.Dockerfile -t yutfut/vvti_order:${GITHUB_SHA::8} .
      - name: Push the image order
        run: docker push yutfut/vvti_order:${GITHUB_SHA::8}


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd vvti/
            touch .env
            echo VERSION=${GITHUB_SHA::8} >> .env
            sudo docker-compose stop
            sudo docker rm -f $(sudo docker ps -aq)
            sudo docker-compose up -d

